GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impib25kIiwiaWQiOiI2MzYzZTdhYmQ5OWM5ZDViYmQ0OTNiZmQiLCJpYXQiOjE2Njc1MDA0NTEsImV4cCI6MTY2NzUwNDA1MX0.NiOQB-UcMGD5JIHoKtQ9AEA5FRmvLck2ZHXKD0dycnQ
